(cl:in-package ublox_msg-msg)
(cl:export '(I_TOW-VAL
          I_TOW
          YEAR-VAL
          YEAR
          MONTH-VAL
          MONTH
          DAY-VAL
          DAY
          HOUR-VAL
          HOUR
          MIN-VAL
          MIN
          SEC-VAL
          SEC
          VALID_DATA-VAL
          VALID_DATA
          T_ACC-VAL
          T_ACC
          NANO-VAL
          NANO
          FIX_TYPE-VAL
          FIX_TYPE
          FLAGS_DATA-VAL
          FLAGS_DATA
          FLAGS2_DATA-VAL
          FLAGS2_DATA
          NUM_SV-VAL
          NUM_SV
          LON-VAL
          LON
          LAT-VAL
          LAT
          HEIGHT-VAL
          HEIGHT
          H_MSL-VAL
          H_MSL
          H_ACC-VAL
          H_ACC
          V_ACC-VAL
          V_ACC
          VEL_N-VAL
          VEL_N
          VEL_E-VAL
          VEL_E
          VEL_D-VAL
          VEL_D
          G_SPEED-VAL
          G_SPEED
          HEAD_MOT-VAL
          HEAD_MOT
          S_ACC-VAL
          S_ACC
          HEAD_ACC-VAL
          HEAD_ACC
          P_DOP-VAL
          P_DOP
          FLAGS3_DATA-VAL
          FLAGS3_DATA
          RESERVED0-VAL
          RESERVED0
          HEAD_VEH-VAL
          HEAD_VEH
          MAG_DEC-VAL
          MAG_DEC
          MAG_ACC-VAL
          MAG_ACC
))