// Generated by gencpp from file ublox_msg/Flags2.msg
// DO NOT EDIT!


#ifndef UBLOX_MSG_MESSAGE_FLAGS2_H
#define UBLOX_MSG_MESSAGE_FLAGS2_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace ublox_msg
{
template <class ContainerAllocator>
struct Flags2_
{
  typedef Flags2_<ContainerAllocator> Type;

  Flags2_()
    : confirmed_avai(0)
    , confirmed_date(0)
    , confirmed_time(0)  {
    }
  Flags2_(const ContainerAllocator& _alloc)
    : confirmed_avai(0)
    , confirmed_date(0)
    , confirmed_time(0)  {
  (void)_alloc;
    }



   typedef uint8_t _confirmed_avai_type;
  _confirmed_avai_type confirmed_avai;

   typedef uint8_t _confirmed_date_type;
  _confirmed_date_type confirmed_date;

   typedef uint8_t _confirmed_time_type;
  _confirmed_time_type confirmed_time;





  typedef boost::shared_ptr< ::ublox_msg::Flags2_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ublox_msg::Flags2_<ContainerAllocator> const> ConstPtr;

}; // struct Flags2_

typedef ::ublox_msg::Flags2_<std::allocator<void> > Flags2;

typedef boost::shared_ptr< ::ublox_msg::Flags2 > Flags2Ptr;
typedef boost::shared_ptr< ::ublox_msg::Flags2 const> Flags2ConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ublox_msg::Flags2_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ublox_msg::Flags2_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::ublox_msg::Flags2_<ContainerAllocator1> & lhs, const ::ublox_msg::Flags2_<ContainerAllocator2> & rhs)
{
  return lhs.confirmed_avai == rhs.confirmed_avai &&
    lhs.confirmed_date == rhs.confirmed_date &&
    lhs.confirmed_time == rhs.confirmed_time;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::ublox_msg::Flags2_<ContainerAllocator1> & lhs, const ::ublox_msg::Flags2_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace ublox_msg

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::ublox_msg::Flags2_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ublox_msg::Flags2_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ublox_msg::Flags2_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ublox_msg::Flags2_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ublox_msg::Flags2_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ublox_msg::Flags2_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ublox_msg::Flags2_<ContainerAllocator> >
{
  static const char* value()
  {
    return "83c735463313d387fad8bf1848b02c03";
  }

  static const char* value(const ::ublox_msg::Flags2_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x83c735463313d387ULL;
  static const uint64_t static_value2 = 0xfad8bf1848b02c03ULL;
};

template<class ContainerAllocator>
struct DataType< ::ublox_msg::Flags2_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ublox_msg/Flags2";
  }

  static const char* value(const ::ublox_msg::Flags2_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ublox_msg::Flags2_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint8 confirmed_avai\n"
"uint8 confirmed_date\n"
"uint8 confirmed_time\n"
;
  }

  static const char* value(const ::ublox_msg::Flags2_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ublox_msg::Flags2_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.confirmed_avai);
      stream.next(m.confirmed_date);
      stream.next(m.confirmed_time);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Flags2_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ublox_msg::Flags2_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ublox_msg::Flags2_<ContainerAllocator>& v)
  {
    s << indent << "confirmed_avai: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.confirmed_avai);
    s << indent << "confirmed_date: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.confirmed_date);
    s << indent << "confirmed_time: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.confirmed_time);
  }
};

} // namespace message_operations
} // namespace ros

#endif // UBLOX_MSG_MESSAGE_FLAGS2_H
